services:
  - type: cron
    name: daily-digest-job
    env: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 0 * * *"
    dockerCommand: uv run python main.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MY_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: VERTEX_PROJECT_ID
        sync: false
      - key: VERTEX_LOCATION
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false